config/routes.rb
Fashionflash::Application.routes.draw do
  resources :comments

  devise_for :users

  resources :ideas
  resources :users do
    resources :ideas, controller: 'user_ideas'
  end
  

  root :to => 'ideas#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:update, :destroy], Idea, :user_id => user.id if user
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :idea

  attr_accessible :body, :idea_id, :user_name
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	has_many :comments

  attr_accessible :description, :name, :picture

  belongs_to :user

  mount_uploader :picture, FlashpicUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login
  ## attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    if params[:id]
      @ideas = Idea.where(:id => params[:id])
    else
      @ideas = Idea.all
    end
  end


  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])
    @comment = @idea.comments.build


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])
    @idea.name = current_user.username
    @idea.user_id = current_user.id

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Flash was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Flash was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_ideas_controller.rb
class UserIdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.where(:user_id => params[:user_id]).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :idea_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Body</th>
    <th>Idea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.idea_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/comments/new.html.erb
<h1>New comment</h1>

<% if user_signed_in? %>
<%= render 'form' %>
<% else %>
	<h4>To make a comment, please login</h4>
<% end %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>User name:</b>
  <%= @comment.user_name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b></b>
  <% @comment.idea_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= current_user.username %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit "flash it" %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing flash</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing flash</h1>

<li>
  

<% @ideas.each do |idea| %>
  <div class="jumbotron">
    <ul>
      <td><%= link_to idea.name, [idea.user, :ideas] %></td>
      
    </ul>
    <ul>
      <td><%= image_tag idea.picture_url, :width => '250' if idea.picture.present? %></td>
      <td><%= link_to idea.description, idea %></td>
    </ul>

    <ul>
      <td><%= link_to 'Show', idea %></td>
      <td>
      <% if can? :update, idea %>
        <%= link_to '| Edit', edit_idea_path(idea) %>
      <% end %>
      </td> 
      <td>
        <% if can? :destroy, idea %>
        <%= link_to '| Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </ul>
    </div>
<% end %>
</li>

<br />

<% if can? :update, @idea %>
<%= link_to 'New flash', new_idea_path %>
<% end %>

app/views/ideas/new.html.erb
<h1>New flash</h1>

<% if user_signed_in? %>
<%= render 'form' %>
<% else %>
	<h4>To flash, please login</h4>
<% end %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <b>Name:</b>
  <%= @idea.name %>
</p>

<p>
	<% if @idea.picture.present? %>		
  <b></b>
  <%= image_tag(@idea.picture_url, :width => "60%")  %>
  <% end %>
</p>

<p>
  <b>Description:</b>
  <%= @idea.description %>
</p>

<% if can? :update, @idea %>
<%= link_to 'Edit', edit_idea_path(@idea) %> |
<% end %>
<%= link_to 'Back', ideas_path %>
<br />
<p><b><%= link_to 'Comments', comments_path%></b></p>
<% @idea.comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %><p>
  </div>
<% end %>
<% if user_signed_in? %>
<%= render 'comments/form' %>
<% else %>
  <p><b>To make a comment, please login first!</b></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fashionflash</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
  <div class="navbar navbar-fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Fashionflash</a>
      <div class="nav-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">home</a></li>
        <li ><%= link_to 'New flash', new_idea_path %></li>
      </ul>
      
      <ul class="nav navbar-nav pull-right">
        
    	<% if user_signed_in? %>
      		<li><%= link_to current_user.username %></li>
      		<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
      		<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
    	<% else %>
    	  <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> 
    	  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
	   <% end %>
      
      </ul>
  </div>
	</div>
  
</div>

<div class="container">
	<% if notice %>
  		<p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-error"><%= alert %></p>
	<% end %>
  <%= yield %>
</div>

<footer>
  <div class="modal-footer">
    Thereza <%= link_to 'github', 'https://github.com/bakerstreet221b' %>
  </div>

</footer>

</body>
</html>

app/views/user_ideas/index.html.erb
<h1><%= @ideas.first.name %></h1>

<table>
  <tr>
    <th>Description</th>
    <th>Picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= link_to idea.description, idea %></td>
    <td><%= image_tag idea.picture_url, :width => '10%' if idea.picture.present?%></td>

    <td>
      <% if can? :update, idea %>
        <%= link_to 'Edit', edit_idea_path(idea) %>
      <% end %>
    </td>
    <td>
      <% if can? :destroy, idea %>
        <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'back', ideas_path %>